### PR TITLE
Added the parsers object to the virtual serial port.

### PR DESCRIPTION
**Pull request by luzlab**
Pretty simple, just copied the parsers property from the real SerialPort to the VirtualSerialPort. The parsers don't actually do anything - but they do let you use the virtual serial port if your code expects SerialPort.parsers to be present.

### CODE REVIEW

**Comment by ecksun** [comment]
While I do like the elegance in this patch there is a certain danger in depending on the library we are trying to replace.

Consider for example if someone is using proxyquire to replace serialport you are going to have a circular dependency.

Likewise, one of the nice things about virtual-serialport is that it does not require any compilation, which node-serialport does (this is in fact something I'm utilizing).

Thus I would suggest, if the licenses allows it, that you rather copy the code, its not as elegant but would give a much better separation between virtual-serialport and node-serialport, which is the purpose of the package.

**Comment by reyiyo** [comment]
@luzlab thank you very much for the patch! I agree with @ecksun. Maybe it's better to copy the code instead of having that dependency. Sometimes I need to use serialport on windows and it is kind of a pain to deal with.

I think there is no problem with the licences, but we can change it to MIT to be sure.

**Comment by luzlab** [comment]
My thinking on this was that any project that uses virtual-serialport will also require serialport, this won't add any additional dependancies introduced. I also changed the version to \* so that it'll just work with whatever version of serial port the project requires.

That said, I understand about the pain of compiling serialport. How do you avoid this currently?

In any case, I'll look into copying the code but my concern is supporting all the different versions of serialport might get messy if we're copying code.

--EDIT---
I just checked the serialport repo and saw the most recent commit changed the name of the readline parser... I know this isn't the first time the name of this parser has changed. If we copy the code (and all the historical variations), then the challenge becomes which version should be exposed. Is there a way to programmatically detect which version of serialport is installed? If so, we'd have to make a lengthy case statement to check the version and expose the right api. Or we could just expose all of the different parsers (ie. always expose ReadLine, Readline, readline, etc). The problem with the first approach is that it's complicated and error-prone - ideally, you'd want to test every version of serialport and check for  The problem with the second is that the virtual api no longer is the same as the api of serialport.

**Comment by ecksun** [comment]
You do raise a valid point that it is difficult to track different versions.

> That said, I understand about the pain of compiling serialport. How do you avoid this currently?

You can avoid it by declaring virtualport an optional dependency

> I just checked the serialport repo and saw the most recent commit changed the name of the readline parser

Do you know if they consider that a breaking change? (I would).

Perhaps the bigger discussion we should be having is how we deal with multiple versions of node-serialport. Should we create a separate issue for that perhaps?

**Comment by luzlab** [comment]
Regarding the recent change in serialport, I think it's just a filename change. Honestly, I'm still a little traumatized from trying to upgrade the serialport version in my app (currently pinned at v2.x)! LOL.

Would making serialport an optional dependency work?

**Pull request merged**
